[licenses]
unlicensed = "deny"

# Deny licenses unless they are specifically listed here
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

# Commented license types are allowed but not currently used
allow = [
    "Apache-2.0",
    # "BSD-2-Clause",
    # "BSD-3-Clause",
    "BSL-1.0",
    # "CC0-1.0",
    # "ISC",
    "MIT",
    # "OpenSSL",
    # "Unlicense",
    # "Zlib",
]

exceptions = [
    { name = "unicode-ident", allow = ["MIT", "Apache-2.0", "Unicode-DFS-2016"] },
]

[bans]
# Deny multiple versions or wildcard dependencies.
multiple-versions = "deny"
wildcards = "deny"

skip = [
    # snafu is using an older version of syn   
    { name = "syn", version = "1" },

    # bottlerocket-settings-sdk and bottlerocket-template-helper are circularly dependent,
    # bottlerocket-template-helper has a dev-dependency on the settings-sdk for tests.
    # In order to bootstrap releases on crates.io, we must drop the `version` requirement the first
    # time that we publish bottlerocket-template-helper
    { name = "bottlerocket-template-helper", version = "*" }
]
