name: Lint Commit Messages
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  commitlint:
    if: github.repository == 'bottlerocket-os/bottlerocket-settings-sdk'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install commitlint @commitlint/config-conventional
      - name: Run commitlint against commits in PR
        env:
          WORKSPACE: ${{ github.workspace }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          npx commitlint \
            -g "${WORKSPACE}/.commitlint.config.mjs" \
            --from "${BASE_SHA}" \
            --to "${HEAD_SHA}" \
            --help-url="https://github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_BASE_REF}/CONTRIBUTING.md" \
            --verbose
